### ISSUE TITLE
Implement adding Tweet images to Open311

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/palautebot#23]

**Comment by igordavydsson** [comment]
Well, seems like it cannot be tested with a test instance of Open311 API.

We already send images with our feedback [here](https://github.com/City-of-Helsinki/palautebot/blob/master/feedback/twitter.py#L240).

[Open311 API docs](https://dev.hel.fi/apis/open311/) say that the API can only accept `http` media links, so maybe we would need to change [this line](https://github.com/City-of-Helsinki/palautebot/blob/master/feedback/twitter.py#L240):
from
`ticket_dict['media_url'] = tweet_media[0]['media_url_https']`
to
`ticket_dict['media_url'] = tweet_media[0]['media_url']`
That way we will pass an `http` link to tweet's image.

I tried doing that and made a couple of POST requests, which both seem to have an image attached now:
1. https://dev.hel.fi/open311-test/v1/requests/c2317019c17350ac32aa5ada1d9022cd1d0914ca.json
This one was created with `tweet_media[0]['media_url']`.
2. https://dev.hel.fi/open311-test/v1/requests/c9bde599c472747f413f4500d5254f473ffabbda.json
This one was created with `tweet_media[0]['media_url_https']`

But their `media_url` links do not open. None of the `media_url` links open at the test API for Open311. 

However, most of the `media_url` links seem to open in [Open311 production instance](https://asiointi.hel.fi/palautews/rest/v1/requests.json). So, I suppose if `tweet_media[0]['media_url_https']` does not work already, then `tweet_media[0]['media_url']` should.

**Comment by igordavydsson** [comment]
@jussiarpalahti ^

**Comment by igordavydsson** [comment]
@tituomin ^

**Comment by igordavydsson** [comment]
**UPDATE**:
according to @tituomin open311 production can also save https links to media files. so, current implementation should already work. closing.
