### ISSUE TITLE
Enable sending Tweets as direct messages to bot (by Twitter users followed by the bot)

### ISSUE THREAD

**Issue by MarjattaPeltonen** [City-of-Helsinki/palautebot#27]

**Comment by MarjattaPeltonen** [comment]
I tested the bot yesterday and didn´t manage to send Tweets as direct messages to bot as before.

**Comment by igordavydsson** [comment]
Two options:
1. Manually make bot follow all invloved Helsinki City workers.
2. Allow to "Receive Direct Msssages from anyone" in bot's account settings.

**Comment by MarjattaPeltonen** [comment]
Hi! Let´s go for option number 1: Manually make bot follow all involved Helsinki City Workers. 

The bot already follows most important accounts.

**Comment by igordavydsson** [comment]
OK, no code changes required either way :)
