### ISSUE TITLE
Prevent reacting to @helpalaute mentions in responses/comments from the feedback system.

### ISSUE THREAD

**Issue by MarjattaPeltonen** [City-of-Helsinki/palautebot#28]

**Comment by MarjattaPeltonen** [comment]
The bot reacts to @helpalaute mentions also when they are made in a response from the Helsinki feedback system. The bot sends it's own responses/comments as new Tweets to the system. This should not be the case.

**Comment by igordavydsson** [comment]
Closed by #34
